# --hf-repo unsloth/Qwen3.5-35B-A3B-GGUF:Q4_K_M
# --hf-repo unsloth/Qwen3.5-9B-GGUF:UD-Q4_K_XL

services:
  llama:
    image: local/llama.cpp:full
    container_name: llama
    ports:
      - 8000:80
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/models:/models
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/.cache:/root/.cache
    env_file:
      - .env
    # entrypoint: sleep 3600
    entrypoint: >
      /app/llama-server
      --hf-repo unsloth/Qwen3.5-4B-GGUF:Q4_K_M
      --ctx-size 16384
      --threads 12
      --alias "unsloth/Qwen3.5-4B-GGUF"
      --host 0.0.0.0
      --port 80
    # restart: unless-stopped
